export const THEMES = [
  {
    name: 'default',
    label: 'default',
    colors: {
      primary: '#4F46E5',
      text: '#111827',
      background: '#FFFFFF',
      darkPrimary: '#7A7CEB',
      darkText: '#FFFFFF',
      darkBackground: '#1A202C',
    },
  },
  {
    name: 'aqua',
    label: 'Aqua',
    colors: {
      primary: '#06B6D4',
      text: '#FFFFFF',
      background: '#0891B2',
      darkPrimary: '#0E7490',
      darkText: '#FFFFFF',
      darkBackground: '#164E63',
    },
  },
  {
    name: 'minimal-light',
    label: 'Minimal Light',
    colors: {
      primary: '#000000',
      text: '#000000',
      background: '#FFFFFF',
      darkPrimary: '#FFFFFF',
      darkText: '#FFFFFF',
      darkBackground: '#1A202C',
    },
  },
  {
    name: 'coral',
    label: 'Coral',
    colors: {
      primary: '#F43F5E',
      text: '#FFFFFF',
      background: '#E11D48',
      darkPrimary: '#FF5252',
      darkText: '#FFFFFF',
      darkBackground: '#B91C1C',
    },
  },
  {
    name: 'pattern-light',
    label: 'Pattern Light',
    colors: {
      primary: '#1F2937',
      text: '#1F2937',
      background: '#F3F4F6',
      darkPrimary: '#1F2937',
      darkText: '#1F2937',
      darkBackground: '#1A202C',
    },
  },
  {
    name: 'yellow-line',
    label: 'Yellow Line',
    colors: {
      primary: '#EAB308',
      text: '#000000',
      background: '#FFFFFF',
      darkPrimary: '#F59E0B',
      darkText: '#000000',
      darkBackground: '#1A202C',
    },
  },
  {
    name: 'mint',
    label: 'Mint',
    colors: {
      primary: '#10B981',
      text: '#FFFFFF',
      background: '#059669',
      darkPrimary: '#34C759',
      darkText: '#FFFFFF',
      darkBackground: '#047857',
    },
  },
  {
    name: 'wave-pink',
    label: 'Wave Pink',
    colors: {
      primary: '#EC4899',
      text: '#FFFFFF',
      background: '#DB2777',
      darkPrimary: '#FF69B4',
      darkText: '#FFFFFF',
      darkBackground: '#B91C1C',
    },
  },
  {
    name: 'navy-gradient',
    label: 'Navy Gradient',
    colors: {
      primary: '#1E40AF',
      text: '#FFFFFF',
      background: 'linear-gradient(to right, #1E3A8A, #1E40AF)',
      darkPrimary: '#1E40AF',
      darkText: '#FFFFFF',
      darkBackground: 'linear-gradient(to right, #1A202C, #1A202C)',
    },
  },
  {
    name: 'purple-gradient',
    label: 'Purple Gradient',
    colors: {
      primary: '#7C3AED',
      text: '#FFFFFF',
      background: 'linear-gradient(to right, #6D28D9, #7C3AED)',
      darkPrimary: '#7C3AED',
      darkText: '#FFFFFF',
      darkBackground: 'linear-gradient(to right, #1A202C, #1A202C)',
    },
  },
  {
    name: 'mint-gradient',
    label: 'Mint Gradient',
    colors: {
      primary: '#059669',
      text: '#FFFFFF',
      background: 'linear-gradient(to right, #047857, #059669)',
      darkPrimary: '#059669',
      darkText: '#FFFFFF',
      darkBackground: 'linear-gradient(to right, #1A202C, #1A202C)',
    },
  },
  {
    name: 'blue-solid',
    label: 'Blue Solid',
    colors: {
      primary: '#2563EB',
      text: '#FFFFFF',
      background: '#1D4ED8',
      darkPrimary: '#2563EB',
      darkText: '#FFFFFF',
      darkBackground: '#1A202C',
    },
  },
  {
    name: 'orange-gradient',
    label: 'Orange Gradient',
    colors: {
      primary: '#EA580C',
      text: '#FFFFFF',
      background: 'linear-gradient(to right, #C2410C, #EA580C)',
      darkPrimary: '#EA580C',
      darkText: '#FFFFFF',
      darkBackground: 'linear-gradient(to right, #1A202C, #1A202C)',
    },
  },
  {
    name: 'peach-gradient',
    label: 'Peach Gradient',
    colors: {
      primary: '#FB7185',
      text: '#FFFFFF',
      background: 'linear-gradient(to right, #F43F5E, #FB7185)',
      darkPrimary: '#FB7185',
      darkText: '#FFFFFF',
      darkBackground: 'linear-gradient(to right, #1A202C, #1A202C)',
    },
  },
  {
    name: 'gray',
    label: 'Gray',
    colors: {
      primary: '#4B5563',
      text: '#FFFFFF',
      background: '#374151',
      darkPrimary: '#4B5563',
      darkText: '#FFFFFF',
      darkBackground: '#1A202C',
    },
  },
  {
    name: 'dark',
    label: 'Dark',
    colors: {
      primary: '#FFFFFF',
      text: '#FFFFFF',
      background: '#111827',
      darkPrimary: '#FFFFFF',
      darkText: '#FFFFFF',
      darkBackground: '#111827',
    },
  },
];

export const SOCIAL_PLATFORMS = [
  { id: 'twitter', name: 'Twitter', icon: 'twitter' },
  { id: 'instagram', name: 'Instagram', icon: 'instagram' },
  { id: 'facebook', name: 'Facebook', icon: 'facebook' },
  { id: 'linkedin', name: 'LinkedIn', icon: 'linkedin' },
  { id: 'youtube', name: 'YouTube', icon: 'youtube' },
  { id: 'github', name: 'GitHub', icon: 'github' },
  { id: 'tiktok', name: 'TikTok', icon: 'tiktok' },
];
