export const THEMES = [
  {
    name: 'default',
    label: 'default',
    colors: {
      primary: '#4F46E5',
      text: '#111827',
      background: '#FFFFFF',
      darkPrimary: '#7A7CEB',
      darkText: '#FFFFFF',
      darkBackground: '#1A202C',
    },
  },
  {
    name: 'minimal',
    label: 'Minimal',
    colors: {
      primary: '#0f172a',
      text: '#334155',
      background: '#ffffff',
      darkPrimary: '#e2e8f0',
      darkText: '#cbd5e1',
      darkBackground: '#0f172a',
    },
  },
  {
    name: 'ocean',
    label: 'Ocean',
    colors: {
      primary: '#0891b2',
      text: '#164e63',
      background: '#ecfeff',
      darkPrimary: '#67e8f9',
      darkText: '#a5f3fc',
      darkBackground: '#083344',
    },
  },
  {
    name: 'forest',
    label: 'Forest',
    colors: {
      primary: '#166534',
      text: '#14532d',
      background: '#f0fdf4',
      darkPrimary: '#86efac',
      darkText: '#bbf7d0',
      darkBackground: '#052e16',
    },
  },
  {
    name: 'sunset',
    label: 'Sunset',
    colors: {
      primary: '#c2410c',
      text: '#7c2d12',
      background: '#fff7ed',
      darkPrimary: '#fb923c',
      darkText: '#fed7aa',
      darkBackground: '#431407',
    },
  },
  {
    name: 'rose-garden',
    label: 'Rose Garden',
    colors: {
      primary: '#be123c',
      text: '#881337',
      background: '#fff1f2',
      darkPrimary: '#fda4af',
      darkText: '#fecdd3',
      darkBackground: '#4c0519',
    },
  },
  {
    name: 'lavender',
    label: 'Lavender',
    colors: {
      primary: '#7e22ce',
      text: '#581c87',
      background: '#faf5ff',
      darkPrimary: '#d8b4fe',
      darkText: '#e9d5ff',
      darkBackground: '#3b0764',
    },
  },
  {
    name: 'emerald',
    label: 'Emerald',
    colors: {
      primary: '#059669',
      text: '#065f46',
      background: '#ecfdf5',
      darkPrimary: '#6ee7b7',
      darkText: '#a7f3d0',
      darkBackground: '#022c22',
    },
  },
  {
    name: 'sky',
    label: 'Sky',
    colors: {
      primary: '#0284c7',
      text: '#075985',
      background: '#f0f9ff',
      darkPrimary: '#7dd3fc',
      darkText: '#bae6fd',
      darkBackground: '#082f49',
    },
  },
  {
    name: 'amber',
    label: 'Amber',
    colors: {
      primary: '#d97706',
      text: '#92400e',
      background: '#fffbeb',
      darkPrimary: '#fcd34d',
      darkText: '#fde68a',
      darkBackground: '#451a03',
    },
  },
  {
    name: 'slate',
    label: 'Slate',
    colors: {
      primary: '#475569',
      text: '#334155',
      background: '#f8fafc',
      darkPrimary: '#94a3b8',
      darkText: '#cbd5e1',
      darkBackground: '#0f172a',
    },
  },
  {
    name: 'indigo',
    label: 'Indigo',
    colors: {
      primary: '#4f46e5',
      text: '#3730a3',
      background: '#eef2ff',
      darkPrimary: '#a5b4fc',
      darkText: '#c7d2fe',
      darkBackground: '#1e1b4b',
    },
  },
  {
    name: 'rose-gold',
    label: 'Rose Gold',
    colors: {
      primary: '#e11d48',
      text: '#9f1239',
      background: '#fff1f2',
      darkPrimary: '#fda4af',
      darkText: '#fecdd3',
      darkBackground: '#4c0519',
    },
  },
  {
    name: 'teal',
    label: 'Teal',
    colors: {
      primary: '#0d9488',
      text: '#115e59',
      background: '#f0fdfa',
      darkPrimary: '#5eead4',
      darkText: '#99f6e4',
      darkBackground: '#042f2e',
    },
  },
  {
    name: 'violet',
    label: 'Violet',
    colors: {
      primary: '#7c3aed',
      text: '#5b21b6',
      background: '#f5f3ff',
      darkPrimary: '#c4b5fd',
      darkText: '#ddd6fe',
      darkBackground: '#2e1065',
    },
  },
  {
    name: 'fuchsia',
    label: 'Fuchsia',
    colors: {
      primary: '#c026d3',
      text: '#86198f',
      background: '#fdf4ff',
      darkPrimary: '#e879f9',
      darkText: '#f5d0fe',
      darkBackground: '#4a044e',
    },
  },
  {
    name: 'lime',
    label: 'Lime',
    colors: {
      primary: '#65a30d',
      text: '#3f6212',
      background: '#f7fee7',
      darkPrimary: '#a3e635',
      darkText: '#bef264',
      darkBackground: '#1a2e05',
    },
  },
  {
    name: 'cyan',
    label: 'Cyan',
    colors: {
      primary: '#0891b2',
      text: '#155e75',
      background: '#ecfeff',
      darkPrimary: '#67e8f9',
      darkText: '#a5f3fc',
      darkBackground: '#083344',
    },
  },
  {
    name: 'zinc',
    label: 'Zinc',
    colors: {
      primary: '#52525b',
      text: '#3f3f46',
      background: '#fafafa',
      darkPrimary: '#a1a1aa',
      darkText: '#d4d4d8',
      darkBackground: '#18181b',
    },
  },
  {
    name: 'neutral',
    label: 'Neutral',
    colors: {
      primary: '#525252',
      text: '#404040',
      background: '#fafafa',
      darkPrimary: '#a3a3a3',
      darkText: '#d4d4d4',
      darkBackground: '#171717',
    },
  },
];

export const SOCIAL_PLATFORMS = [
  { id: 'twitter', name: 'Twitter', icon: 'twitter' },
  { id: 'instagram', name: 'Instagram', icon: 'instagram' },
  { id: 'facebook', name: 'Facebook', icon: 'facebook' },
  { id: 'linkedin', name: 'LinkedIn', icon: 'linkedin' },
  { id: 'youtube', name: 'YouTube', icon: 'youtube' },
  { id: 'github', name: 'GitHub', icon: 'github' },
  { id: 'tiktok', name: 'TikTok', icon: 'tiktok' },
];
