export { default as ComparisonTableSection } from './ComparisonTableSection';
export { default as CTASection } from './CTASection';
export { default as FAQSection } from './FAQSection';
export { default as Footer } from './Footer';
export { default as GuaranteeSection } from './GuaranteeSection';
export { default as Header } from './Header';
export { default as PriceHeroSection } from './PriceHeroSection';
export { default as PricingPlansSection } from './PricingPlansSection';
export { default as TestimonialsSection } from './TestimonialsSection';
